external_root: external/SecurePrompt

inputs:
  prompts:
    - "${external_root}/PROMPTS/**/*.xlsx"
    - "${external_root}/PROMPTS/**/*.csv"
    - "${external_root}/PROMPTS/**/*.jsonl"
    - "${external_root}/PROMPTS/**/*.txt"
  data:
    - "${external_root}/DATA/**/*.xlsx"
    - "${external_root}/DATA/**/*.csv"
    - "${external_root}/DATA/**/*.jsonl"
    - "${external_root}/DATA/**/*.txt"
    - "${external_root}/DATA/**/*.pdf"
    - "${external_root}/DATA/**/*.png"
    - "${external_root}/DATA/**/*.jpg"
    - "${external_root}/DATA/**/*.jpeg"

policy_hints: []

output:
  golden_dir: data/golden
  eval_dir: data/eval
  policy_dir: policy/manifests
