generated_from: PROMPTS
total_labels: 285
labels:
- label: ACCOUNT_BALANCE
  c_level: C2
  examples: 12
- label: AGE
  c_level: C2
  examples: 12
- label: AGREEMENT
  c_level: C2
  examples: 20
- label: AGREEMENT_ID
  c_level: C2
  examples: 106
- label: AGREEMENT_TYPE
  c_level: C2
  examples: 38
- label: AMOUNT
  c_level: C2
  examples: 378
- label: AMOUNT_LIST
  c_level: C2
  examples: 2
- label: APP
  c_level: C2
  examples: 4
- label: APPLICABILITY
  c_level: C2
  examples: 16
- label: APPLICATION_NAME
  c_level: C2
  examples: 24
- label: APPLICATION_TYPE
  c_level: C2
  examples: 4
- label: APPROVAL_A
  c_level: C2
  examples: 4
- label: APPROVAL_AUTHORITY
  c_level: C2
  examples: 2
- label: APPROVAL_B
  c_level: C2
  examples: 4
- label: APPROVAL_LEVEL
  c_level: C2
  examples: 74
- label: APPROVER_NAME
  c_level: C2
  examples: 8
- label: APPS
  c_level: C2
  examples: 4
- label: APP_A
  c_level: C2
  examples: 6
- label: APP_B
  c_level: C2
  examples: 6
- label: APP_C
  c_level: C2
  examples: 6
- label: APP_D
  c_level: C2
  examples: 4
- label: APP_E
  c_level: C2
  examples: 4
- label: APP_LIST
  c_level: C2
  examples: 38
- label: APP_LIST_SHORT
  c_level: C2
  examples: 24
- label: APP_LIST_WITH_CAPACITY
  c_level: C2
  examples: 8
- label: APP_NAME
  c_level: C2
  examples: 46
- label: ASSET_OWNER
  c_level: C2
  examples: 34
- label: ASSET_OWNER_EMAIL
  c_level: C2
  examples: 2
- label: AUTH_METHOD
  c_level: C2
  examples: 18
- label: AUTOMATION_STATUS
  c_level: C2
  examples: 96
- label: BENEFICIARY
  c_level: C2
  examples: 4
- label: BENEFICIARY_NAME
  c_level: C2
  examples: 2
- label: BIOMETRIC_TYPE
  c_level: C2
  examples: 10
- label: CATEGORY
  c_level: C2
  examples: 56
- label: CATEGORY_WRONG
  c_level: C2
  examples: 8
- label: CAT_A
  c_level: C2
  examples: 10
- label: CAT_B
  c_level: C2
  examples: 10
- label: CCV
  c_level: C2
  examples: 12
- label: CHANNELS
  c_level: C2
  examples: 40
- label: CITY
  c_level: C2
  examples: 100
- label: COMPANY
  c_level: C2
  examples: 8
- label: CONFIG
  c_level: C2
  examples: 2
- label: CONFIG_A
  c_level: C2
  examples: 4
- label: CONFIG_B
  c_level: C2
  examples: 4
- label: CONFIG_C
  c_level: C2
  examples: 4
- label: CONFIG_D
  c_level: C2
  examples: 4
- label: CONFIG_E
  c_level: C2
  examples: 4
- label: CONFIG_GROUP
  c_level: C2
  examples: 26
- label: CONFIG_GROUP_LIST
  c_level: C2
  examples: 4
- label: CONTRACT_TYPE
  c_level: C2
  examples: 12
- label: CONTRIB
  c_level: C2
  examples: 16
- label: CORPKEY
  c_level: C2
  examples: 16
- label: COST_A
  c_level: C2
  examples: 4
- label: COST_B
  c_level: C2
  examples: 4
- label: COST_C
  c_level: C2
  examples: 4
- label: COST_CENTER
  c_level: C2
  examples: 24
- label: COST_D
  c_level: C2
  examples: 4
- label: COST_E
  c_level: C2
  examples: 4
- label: COST_MODEL
  c_level: C2
  examples: 18
- label: CREDIT_CARD_NUMBER
  c_level: C2
  examples: 12
- label: CREDIT_SCORE
  c_level: C2
  examples: 16
- label: CRIMINAL_CONVICTIONS
  c_level: C2
  examples: 4
- label: CURRENCY
  c_level: C2
  examples: 238
- label: CUSTOMER
  c_level: C2
  examples: 26
- label: CUSTOMER_NAME
  c_level: C2
  examples: 152
- label: DATE
  c_level: C2
  examples: 224
- label: DATE_A
  c_level: C2
  examples: 40
- label: DATE_B
  c_level: C2
  examples: 40
- label: DATE_C
  c_level: C2
  examples: 12
- label: DATE_LIST
  c_level: C2
  examples: 6
- label: DEPARTMENT
  c_level: C2
  examples: 2
- label: DEPLOYMENT_DATE
  c_level: C2
  examples: 16
- label: DL_ALIAS
  c_level: C2
  examples: 4
- label: DOB
  c_level: C3
  examples: 8
- label: DOC
  c_level: C2
  examples: 8
- label: DOCUMENT_LINK
  c_level: C2
  examples: 30
- label: DOCUMENT_TYPE
  c_level: C2
  examples: 56
- label: DOC_A
  c_level: C2
  examples: 8
- label: DOC_B
  c_level: C2
  examples: 8
- label: DOC_REF
  c_level: C2
  examples: 12
- label: DOC_REFS
  c_level: C2
  examples: 4
- label: DOC_REF_LIST
  c_level: C2
  examples: 10
- label: DOC_TYPE
  c_level: C2
  examples: 8
- label: ELIGIBILITY
  c_level: C2
  examples: 4
- label: EMAIL
  c_level: C3
  examples: 94
- label: EMP
  c_level: C2
  examples: 14
- label: EMP1_CORPKEY
  c_level: C2
  examples: 8
- label: EMP1_EMAIL
  c_level: C2
  examples: 8
- label: EMP1_FIRST
  c_level: C2
  examples: 12
- label: EMP1_LAST
  c_level: C2
  examples: 10
- label: EMP1_NAME
  c_level: C2
  examples: 8
- label: EMP1_PHONE
  c_level: C2
  examples: 16
- label: EMP2_CORPKEY
  c_level: C2
  examples: 8
- label: EMP2_EMAIL
  c_level: C2
  examples: 8
- label: EMP2_FIRST
  c_level: C2
  examples: 12
- label: EMP2_LAST
  c_level: C2
  examples: 10
- label: EMP2_NAME
  c_level: C2
  examples: 8
- label: EMP2_PHONE
  c_level: C2
  examples: 16
- label: EMP_1_EMAIL
  c_level: C2
  examples: 2
- label: EMP_2_EMAIL
  c_level: C2
  examples: 2
- label: EMP_3_EMAIL
  c_level: C2
  examples: 2
- label: EMP_A_CORPKEY
  c_level: C2
  examples: 4
- label: EMP_A_EMAIL
  c_level: C2
  examples: 14
- label: EMP_A_FIRST
  c_level: C2
  examples: 14
- label: EMP_A_LAST
  c_level: C2
  examples: 12
- label: EMP_A_PHONE
  c_level: C2
  examples: 12
- label: EMP_B_CORPKEY
  c_level: C2
  examples: 4
- label: EMP_B_EMAIL
  c_level: C2
  examples: 14
- label: EMP_B_FIRST
  c_level: C2
  examples: 14
- label: EMP_B_LAST
  c_level: C2
  examples: 12
- label: EMP_B_PHONE
  c_level: C2
  examples: 12
- label: EMP_EMAIL
  c_level: C2
  examples: 2
- label: EMP_PHONE
  c_level: C2
  examples: 2
- label: ENTITY
  c_level: C2
  examples: 6
- label: ENTITY_NAME
  c_level: C2
  examples: 30
- label: ENTITY_TYPE
  c_level: C2
  examples: 10
- label: ENV
  c_level: C2
  examples: 6
- label: ENVIRONMENT
  c_level: C2
  examples: 82
- label: ENVIRONMENTS
  c_level: C2
  examples: 2
- label: EXAMPLE_NAME
  c_level: C2
  examples: 12
- label: EXPIRY_DATE
  c_level: C2
  examples: 10
- label: FEES
  c_level: C2
  examples: 26
- label: FIELD
  c_level: C2
  examples: 14
- label: FIELD_A
  c_level: C2
  examples: 8
- label: FIELD_B
  c_level: C2
  examples: 8
- label: FIELD_LIST
  c_level: C2
  examples: 2
- label: FINANCIAL_METRIC
  c_level: C2
  examples: 4
- label: FIRST_LAST
  c_level: C2
  examples: 24
- label: FIRST_NAME
  c_level: C2
  examples: 152
- label: FIRST_NAMES
  c_level: C2
  examples: 2
- label: FIRST_NAME_LIST
  c_level: C2
  examples: 2
- label: FREQUENCY
  c_level: C2
  examples: 112
- label: FULLNAME
  c_level: C2
  examples: 16
- label: FULL_NAME
  c_level: C2
  examples: 54
- label: GB
  c_level: C2
  examples: 2
- label: GUIDELINE_A
  c_level: C2
  examples: 8
- label: GUIDELINE_B
  c_level: C2
  examples: 8
- label: GUIDELINE_NAME
  c_level: C2
  examples: 84
- label: GUIDELINE_STATUS
  c_level: C2
  examples: 48
- label: HOBBIES
  c_level: C2
  examples: 8
- label: HOUSEHOLD_DATA
  c_level: C2
  examples: 4
- label: IBAN
  c_level: C4
  examples: 222
- label: IBAN_EX
  c_level: C2
  examples: 8
- label: ID
  c_level: C2
  examples: 2
- label: ID_NUMBER
  c_level: C2
  examples: 4
- label: INCOME
  c_level: C2
  examples: 58
- label: INSURANCE_POLICY
  c_level: C2
  examples: 4
- label: INSURANCE_TYPE
  c_level: C2
  examples: 2
- label: INTEREST
  c_level: C2
  examples: 16
- label: INTEREST_RATE
  c_level: C2
  examples: 26
- label: IP_ADDRESS
  c_level: C2
  examples: 12
- label: ISSUER_A
  c_level: C2
  examples: 4
- label: ISSUER_B
  c_level: C2
  examples: 8
- label: ISSUING_BODY
  c_level: C2
  examples: 64
- label: ITEMS
  c_level: C2
  examples: 2
- label: ITEMS_LIST
  c_level: C2
  examples: 2
- label: IT_CUSTODIAN
  c_level: C2
  examples: 22
- label: IT_CUSTODIANS
  c_level: C2
  examples: 6
- label: LAST_EXECUTED_DATE
  c_level: C2
  examples: 142
- label: LAST_EXECUTED_DATE_A
  c_level: C2
  examples: 4
- label: LAST_INTERACTION_DATE
  c_level: C2
  examples: 22
- label: LAST_NAME
  c_level: C2
  examples: 126
- label: LAST_REVIEWED_DATE
  c_level: C2
  examples: 148
- label: LINK
  c_level: C2
  examples: 24
- label: LINK_A
  c_level: C2
  examples: 8
- label: LINK_B
  c_level: C2
  examples: 8
- label: LINK_LIST
  c_level: C2
  examples: 2
- label: LINK_Q
  c_level: C2
  examples: 16
- label: LIST
  c_level: C2
  examples: 6
- label: MASKED_PIN
  c_level: C2
  examples: 18
- label: METHOD
  c_level: C2
  examples: 2
- label: NAME
  c_level: C2
  examples: 78
- label: NAME_LIST
  c_level: C2
  examples: 6
- label: NATIONAL_ID
  c_level: C4
  examples: 4
- label: NEW_IT_CUSTODIAN
  c_level: C2
  examples: 2
- label: NUMBER
  c_level: C2
  examples: 4
- label: ONE_LINE
  c_level: C2
  examples: 2
- label: OPERATIONAL_STATUS
  c_level: C2
  examples: 14
- label: OP_STATUS
  c_level: C2
  examples: 72
- label: OWNER
  c_level: C2
  examples: 2
- label: OWNER_MATRIX
  c_level: C2
  examples: 2
- label: OWNER_NAME
  c_level: C2
  examples: 8
- label: PARTY
  c_level: C2
  examples: 16
- label: PARTY_EMAIL
  c_level: C2
  examples: 8
- label: PARTY_NAME
  c_level: C2
  examples: 16
- label: PASSWORD
  c_level: C2
  examples: 10
- label: PAYEE_NAME
  c_level: C2
  examples: 92
- label: PAYEE_OR_PAYER
  c_level: C2
  examples: 4
- label: PAYER_EMAIL
  c_level: C2
  examples: 8
- label: PAYER_NAME
  c_level: C2
  examples: 48
- label: PAYMENT_ORDER_ID
  c_level: C2
  examples: 112
- label: PAYMENT_TYPE
  c_level: C2
  examples: 80
- label: PERIOD
  c_level: C2
  examples: 4
- label: PHONE
  c_level: C3
  examples: 28
- label: PIN
  c_level: C2
  examples: 8
- label: POLICY
  c_level: C2
  examples: 16
- label: POLICY_A
  c_level: C2
  examples: 12
- label: POLICY_ALTERNATIVE
  c_level: C2
  examples: 2
- label: POLICY_B
  c_level: C2
  examples: 12
- label: POLICY_C
  c_level: C2
  examples: 4
- label: POLICY_NAME
  c_level: C2
  examples: 130
- label: POLICY_STATUS
  c_level: C2
  examples: 70
- label: POLITICAL_OPINION
  c_level: C2
  examples: 4
- label: PORTFOLIO_VALUE
  c_level: C2
  examples: 2
- label: POSTAL
  c_level: C2
  examples: 4
- label: PROCESS_A
  c_level: C2
  examples: 6
- label: PROCESS_B
  c_level: C2
  examples: 6
- label: PROCESS_NAME
  c_level: C2
  examples: 164
- label: PROCESS_STATUS
  c_level: C2
  examples: 114
- label: PROD
  c_level: C2
  examples: 12
- label: PRODUCT
  c_level: C2
  examples: 122
- label: PRODUCT_A
  c_level: C2
  examples: 12
- label: PRODUCT_B
  c_level: C2
  examples: 12
- label: PRODUCT_C
  c_level: C2
  examples: 12
- label: PRODUCT_CODE
  c_level: C2
  examples: 32
- label: PRODUCT_NAME
  c_level: C2
  examples: 102
- label: PRODUCT_TYPE
  c_level: C2
  examples: 14
- label: PROD_A
  c_level: C2
  examples: 8
- label: PROD_B
  c_level: C2
  examples: 8
- label: PROD_C
  c_level: C2
  examples: 8
- label: PROVIDER
  c_level: C2
  examples: 38
- label: PROVIDERS
  c_level: C2
  examples: 6
- label: PROVIDER_A
  c_level: C2
  examples: 2
- label: PROVIDER_B
  c_level: C2
  examples: 2
- label: PROVIDER_C
  c_level: C2
  examples: 2
- label: PROVIDER_LIST
  c_level: C2
  examples: 2
- label: REFERENCE
  c_level: C2
  examples: 12
- label: REGULATORY_TAGS
  c_level: C2
  examples: 6
- label: REG_TAGS
  c_level: C2
  examples: 32
- label: REL
  c_level: C2
  examples: 18
- label: RELATIONSHIP
  c_level: C2
  examples: 96
- label: RELATIONSHIP_TYPE
  c_level: C2
  examples: 26
- label: RELIGIOUS_BELIEF
  c_level: C2
  examples: 4
- label: REL_A
  c_level: C2
  examples: 6
- label: REL_B
  c_level: C2
  examples: 6
- label: REL_C
  c_level: C2
  examples: 2
- label: RESPONSIBLE_DEPT
  c_level: C2
  examples: 40
- label: RESPONSIBLE_TEAM
  c_level: C2
  examples: 10
- label: RESP_DEPT
  c_level: C2
  examples: 28
- label: RESP_TEAM
  c_level: C2
  examples: 78
- label: REVIEW_DATE
  c_level: C2
  examples: 24
- label: REVIEW_FREQ
  c_level: C2
  examples: 40
- label: REVIEW_FREQUENCY
  c_level: C2
  examples: 28
- label: REVIEW_FREQ_A
  c_level: C2
  examples: 4
- label: REVIEW_FREQ_B
  c_level: C2
  examples: 4
- label: REVIEW_FREQ_C
  c_level: C2
  examples: 4
- label: ROLE_A
  c_level: C2
  examples: 4
- label: ROLE_B
  c_level: C2
  examples: 4
- label: SERVICE_CHANNEL
  c_level: C2
  examples: 8
- label: SOURCE
  c_level: C2
  examples: 12
- label: START_DATE
  c_level: C2
  examples: 4
- label: STATUS
  c_level: C2
  examples: 516
- label: STATUS_A
  c_level: C2
  examples: 14
- label: STATUS_B
  c_level: C2
  examples: 14
- label: STATUS_C
  c_level: C2
  examples: 4
- label: STATUS_LIST
  c_level: C2
  examples: 12
- label: STORAGE_CAPACITY
  c_level: C2
  examples: 18
- label: STORAGE_GB
  c_level: C2
  examples: 6
- label: STREET
  c_level: C2
  examples: 8
- label: SUMMARY
  c_level: C2
  examples: 2
- label: SUPPORTED_CURRENCIES
  c_level: C2
  examples: 20
- label: SYSTEM_NAME
  c_level: C2
  examples: 10
- label: TARGET_TEAM
  c_level: C2
  examples: 8
- label: TERM
  c_level: C2
  examples: 40
- label: TERM_A
  c_level: C2
  examples: 20
- label: TERM_B
  c_level: C2
  examples: 20
- label: TERM_LAST_REVIEWED_DATE
  c_level: C2
  examples: 18
- label: THRESHOLD
  c_level: C2
  examples: 6
- label: TRANSACTION
  c_level: C2
  examples: 8
- label: TRANSACTION_TYPE
  c_level: C2
  examples: 8
- label: TRANSFER_ID
  c_level: C2
  examples: 222
- label: TRANSFER_ID_LIST
  c_level: C2
  examples: 2
- label: TYPE
  c_level: C2
  examples: 54
- label: TYPE_GROUP
  c_level: C2
  examples: 4
- label: USAGE_SENTENCE
  c_level: C2
  examples: 2
- label: VALUE
  c_level: C2
  examples: 8
- label: VCPU_RAM
  c_level: C2
  examples: 14
- label: VERSION
  c_level: C2
  examples: 32
- label: VIRTUAL_SYSTEM_CONFIGURATION
  c_level: C2
  examples: 4
- label: VM_NAME
  c_level: C2
  examples: 38
- label: WORKSTREAM
  c_level: C2
  examples: 8
- label: YEAR
  c_level: C2
  examples: 98
- label: YEAR_A
  c_level: C2
  examples: 4
- label: YEAR_B
  c_level: C2
  examples: 4
- label: YEAR_RANGE
  c_level: C2
  examples: 4
