placeholders:
  POLICY_NAME: "\\b([A-Z][A-Za-z0-9\-]+(?:\\s[A-Z][A-Za-z0-9\-]+){0,6}\\sPolicy)\\b"
  PRODUCT_NAME: "\\b(Current\\s+Account|Savings\\s+Account|Credit\\s*Card|Travel\\s+Insurance|Life\\s+Insurance|Investment\\s+Portfolio|Personal\\s+Loan)\\b"
  APPLICATION_NAME: "\\bApp[_\\s]?\\d{1,4}\\b"
  PROVIDER: "\\b(AWS|Azure|GCP|Google\\s+Cloud|On[- ]?Prem)\\b"
  SERVICE_CHANNEL: "\\b(web|mobile|branch|call[ -]?center|atm)\\b"
  STATUS: "\\b(active|inactive|retired|pending|terminated|completed|failed|running)\\b"
  AMOUNT: "\\b(?:(?:€|\\$|£)\\s?)?\\d{1,3}(?:[ ,]\\d{3})*(?:[.,]\\d+)?\\b"
  CURRENCY: "\\b(EUR|USD|GBP|CHF)\\b"
  TRANSFER_ID: "\\b(?:TRX|TX|TR|XFER|T)\\d[\\w\\-]{4,}\\b"
  PAYMENT_ORDER_ID: "\\b(?:PO|PAY)\\d[\\w\\-]{4,}\\b"
  IBAN: "\\b[A-Z]{2}\\d{2}[A-Z0-9]{11,30}\\b"
  PROCESS_NAME: "\\b([A-Z][A-Za-z0-9\\-]+(?:\\s[A-Z][A-Za-z0-9\\-]+){0,5})\\s+(?:process|procedure)\\b"
  CUSTOMER_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){1,2})\\b"
  FIRST_NAME: "\\b([A-Z][a-z]{2,})\\b"
  LAST_NAME: "\\b([A-Z][a-z]{2,})\\b"
  LAST_REVIEWED_DATE: "\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\s?[A-Za-z]{3,9}\\s?\\d{2,4})\\b"
  LAST_EXECUTED_DATE: "\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\s?[A-Za-z]{3,9}\\s?\\d{2,4})\\b"
  FREQUENCY: "\\b(bi-?annual|quarterly|monthly|weekly|yearly|annually?)\\b"
  PROCESS_STATUS: "\\b(active|inactive|retired|pending|terminated|completed|failed|running)\\b"
  PAYEE_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){1,2})\\b"
  ENVIRONMENT: "\\b(Production|Acceptance|UAT|Development|Dev|Test|Prod)\\b"
  GUIDELINE_NAME: "['“”‘’]?([A-Z][A-Za-z0-9\- ]{2,60})['“”‘’]?\\s+guideline"
