placeholders:
  AGREEMENT_ID: "\\b([A-Z0-9][A-Z0-9\\-\\_/]{3,})\\b"
  AGREEMENT_TYPE: "\\b(supplier|customer|vendor)\\s+agreements?\\b"
  APPLICATION_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  APPROVER_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  APP_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  COST_MODEL: "\\b(OpEx|CapEx|cost\\s*model|chargeback|showback)\\b"
  CREDIT_CARD_NUMBER: "\\b([A-Z0-9][A-Z0-9\\-\\_/]{3,})\\b"
  CUSTOMER_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  DEPLOYMENT_DATE: "\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\s?[A-Za-z]{3,9}\\s?\\d{2,4})\\b"
  DOCUMENT_LINK: "https?://[^\\s>]+"
  EMAIL: "\\b[A-Za-z0-9._%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,}\\b"
  EMP1_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  EMP2_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  ENTITY_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  ENTITY_TYPE: "\\b(entity|supplier|customer|vendor|partner|application|service)\\b"
  ENVIRONMENT: "\\b(Production|Acceptance|UAT|Development|Dev|Test|Prod)\\b"
  EXAMPLE_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  EXPIRY_DATE: "\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\s?[A-Za-z]{3,9}\\s?\\d{2,4})\\b"
  FIRST_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  FULL_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  GUIDELINE_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  IBAN: "\\b[A-Z]{2}\\d{2}[A-Z0-9]{10,30}\\b"
  ID_NUMBER: "\\b([A-Z0-9][A-Z0-9\\-\\_/]{3,})\\b"
  LAST_EXECUTED_DATE: "\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\s?[A-Za-z]{3,9}\\s?\\d{2,4})\\b"
  LAST_INTERACTION_DATE: "\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\s?[A-Za-z]{3,9}\\s?\\d{2,4})\\b"
  LAST_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  LAST_REVIEWED_DATE: "\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\s?[A-Za-z]{3,9}\\s?\\d{2,4})\\b"
  NATIONAL_ID: "\\b([A-Z0-9][A-Z0-9\\-\\_/]{3,})\\b"
  OWNER_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  PARTY_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  PAYEE_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  PAYER_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  PAYMENT_ORDER_ID: "\\b([A-Z0-9][A-Z0-9\\-\\_/]{3,})\\b"
  POLICY_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  PROCESS_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  PRODUCT_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  PROVIDER: "\\b(AWS|Azure|GCP|Google\\s+Cloud|On[- ]?Prem)\\b"
  REVIEW_DATE: "\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\s?[A-Za-z]{3,9}\\s?\\d{2,4})\\b"
  SERVICE_CHANNEL: "\\b(web|mobile|branch|call[ \\-]?center|atm)\\b"
  START_DATE: "\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\s?[A-Za-z]{3,9}\\s?\\d{2,4})\\b"
  STORAGE_CAPACITY: "\\b\\d+(?:\\.\\d+)?\\s?(GB|MB|TB|GiB|MiB|TiB)\\b"
  SYSTEM_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  TERM_LAST_REVIEWED_DATE: "\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\s?[A-Za-z]{3,9}\\s?\\d{2,4})\\b"
  TRANSACTION_TYPE: "\\b(online|sepa|wire|transfer|direct\\s*debit|card)\\b"
  TRANSFER_ID: "\\b([A-Z0-9][A-Z0-9\\-\\_/]{3,})\\b"
  VM_NAME: "\\b([A-Z][a-z]+(?:\\s[A-Z][a-z]+){0,3})\\b"
  YEAR: "\\b(19|20)\\d{2}\\b"
  YEAR_1: "\\b(19|20)\\d{2}\\b"
  YEAR_2: "\\b(19|20)\\d{2}\\b"
