# config/token_aliases.yml
# Canonical -> list of aliases seen in gold/got. Case-insensitive.
NAME:
  - NAME
  - FIRST
  - LAST
  - EMP1_FIRST
  - EMP1_LAST
  - EMP2_FIRST
  - EMP2_LAST
  - EMP_A_FIRST
  - EMP_A_LAST
  - EMP_B_FIRST
  - EMP_B_LAST
  - EMP1_NAME
  - EMP2_NAME
  - CUSTOMER_NAME
  - OWNER_NAME
  - APPROVER_NAME
  - CONTRIBUTOR_NAME
  - CONTACT_NAME

PHONE:
  - PHONE
  - EMP1_PHONE
  - EMP2_PHONE
  - EMP_A_PHONE
  - EMP_B_PHONE
  - CUSTOMER_PHONE
  - CONTACT_PHONE
  - MOBILE
  - TEL
  - PHONE_NUMBER

EMAIL:
  - EMAIL
  - EMP1_EMAIL
  - EMP2_EMAIL
  - EMP_A_EMAIL
  - EMP_B_EMAIL
  - CUSTOMER_EMAIL
  - CONTACT_EMAIL
  - MAIL

CORPKEY:
  - CORPKEY
  - EMP1_CORPKEY
  - EMP2_CORPKEY
  - CORPKEY_1
  - CORPKEY_2

DATE:
  - DATE
  - DOB
  - D_O_B

IBAN:
  - IBAN
  - ACCOUNT
  - BANK_ACCOUNT

BIC:
  - BIC
  - SWIFT

PAN:
  - PAN
  - CARD
  - CC
  - CREDIT_CARD
  - CARD_NUMBER

RRN:
  - RRN
  - NATIONAL_ID

TRANSFER_ID:
  - TRANSFER_ID
  - TXID
  - TX_ID
  - PAYMENT_ID
  - REFERENCE
  - REF
  - TRANSFER_REF
  - CONFIRMATION
  - CONFIRMATION_CODE

STATUS:
  - STATUS
  - STATE
  - RESULT
  - OUTCOME

# Collapse money signals so gold's AMOUNT/CURRENCY match one detector label.
MONEY:
  - MONEY
  - AMOUNT
  - CURRENCY
  - EUR
  - USD
  - GBP
  - PRICE
  - TOTAL
