# Map noisy or contextual tokens to canonical labels
# (applied to BOTH gold and got side before scoring)
EMP1_EMAIL: EMAIL
EMP2_EMAIL: EMAIL
EMP_A_EMAIL: EMAIL
EMP_B_EMAIL: EMAIL
CUSTOMER_EMAIL: EMAIL
CONTACT_EMAIL: EMAIL

EMP1_PHONE: PHONE
EMP2_PHONE: PHONE
EMP_A_PHONE: PHONE
EMP_B_PHONE: PHONE
CUSTOMER_PHONE: PHONE
CONTACT_PHONE: PHONE
MOBILE: PHONE
TEL: PHONE

EMP1_FIRST: NAME
EMP1_LAST: NAME
EMP2_FIRST: NAME
EMP2_LAST: NAME
EMP_A_FIRST: NAME
EMP_A_LAST: NAME
EMP_B_FIRST: NAME
EMP_B_LAST: NAME
EMP1_NAME: NAME
EMP2_NAME: NAME
OWNER_NAME: NAME
APPROVER_NAME: NAME
CONTACT_NAME: NAME
CUSTOMER_NAME: NAME

CARD: PAN
CREDIT_CARD: PAN
DEBIT_CARD: PAN

BANK_ACCOUNT: IBAN
TRANSFER_ID: TX_ID
TRANSACTION_ID: TX_ID
PAYMENT_ID: TX_ID

CURRENCY_CODE: CURRENCY
AMT: AMOUNT

DT: DATE
DOB: DOB
YOB: YEAR
YMD: DATE
